routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    //return view('welcome');
    return view('layouts.organica.homepage');    
});

Auth::routes();

/*Route::get('emails', function(){
	$user = App\User::inRandomOrder()->first();
	$subject = "Failed Job test";
	$email_view = 'emails.notify_admin';

	//dispatch(new App\Jobs\SendAdminEmail($user, $subject, $email_view));
	dispatch(new App\Jobs\SendAdminEmail($subject, $email_view, "TESTING 24141"));
    echo('done');
});
*/

Route::get('/fb/data-feed', [
	'as' => 'facebook.data.feed',
	'uses' => 'ProductController@facebookDataFeedCSV'
]);

Route::get('/search', [
	'as' => 'search.products',
	'uses' => 'ProductController@searchProducts'
]);

//Route::get('/home', 'HomeController@index');

//Webhooks
Route::post('/membership/stripe-webhooks', [
	'uses' => 'StripeWebhooksController@processWebhook'
	]);

Route::get('/contact-us', function () {
    return view('pages.contact');    
});

Route::get('/terms', function () {
    return view('pages.terms');    
});

Route::get('/privacy-policy', function () {
    return view('pages.privacy');    
});

Route::get('/faqs', function () {
    return view('pages.faqs');    
});

Route::get('/giving-back', function () {
    return view('pages.donations');    
});

Route::get('/shipping', function () {
    return view('pages.shipping');    
});

Route::get('/refunds', function () {
    return view('pages.refunds');    
});

Route::get('/gift-cards', function () {
    return view('gift_cards.index');    
});

Route::get('/subscription', function () {
    return view('pages.subscription');    
});

Route::post('gift-cards', [
			'as' => 'purchase.gift.card',
			'uses' =>'CreditsController@purchaseGiftCard']);

Route::post('credits/redeem', [
			'as' => 'redeem.credit.code',
			'uses' =>'CreditsController@redeemCreditCode']);

Route::get('/{cat_slug}/sub/{subcategory_id}/{sub_slug}/', [
			'as' => 'list.products',
			'uses' =>'SubCategoryController@listProducts']);

Route::get('/{cat_slug}/{sub_slug}/pr/{product_id}/{prod_slug}', [
			'as' => 'product.details',
			'uses'=> 'ProductController@productDetails']);

Route::delete('/cart/empty', [
			'as' =>'empty.cart', 
			'uses' => 'CartController@emptyCart',
		]);
Route::resource('/cart', 'CartController');

//For Account
Route::group(['prefix' => 'my-account', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.account',
		function () {
			if (auth()->user()->hasRole('admin')) {
				return redirect('admin');
			}

			return redirect()->route('user.account', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
		'as' =>'user.account', 
		'uses' => 'UsersController@myAccount',
	]);

	Route::get('/{user_ref_id}/edit', [
		'as' =>'edit.account', 
		'uses' => 'UsersController@editAccount',
	]);

	Route::post('/{user_ref_id}/edit', [
		'as' =>'update.account', 
		'uses' => 'UsersController@updateAccount',
	]);

	Route::post('/cart/reorder/{order_ref_id}', [
				'as' => 'reorder.items',
				'uses' =>'CartController@reorderItems']);	
	
	Route::delete('/cancel-order/{order_ref_id}', [
				'as' => 'cancel.order',
				'uses' => 'OrdersController@cancelOrder'
				]);
	
	Route::get('/credits/{user_ref_id}', [
		'as' =>'user.credits', 
		'uses' => 'CreditsController@myCredits',
	]);

	Route::post('/payment-settings/add/{user_ref_id}', [
		'as' =>'add.card', 
		'uses' => 'UsersController@storeCreditCard',
	]);

	Route::get('/payment-settings/{user_ref_id}', [
		'as' =>'edit.card', 
		'uses' => 'UsersController@editCreditCard',
	]);

	Route::post('/payment-settings/{user_ref_id}', [
		'as' =>'update.card', 
		'uses' => 'UsersController@updateCreditCard',
	]);
});

Route::group(['prefix' => 'my-membership'], function () {
	Route::get('/{user_ref_id}', [
		'as' =>'user.memberships', 
		'uses' => 'UsersController@myMemberships',
	]);
});

Route::group(['prefix' => 'membership'], function () {
	Route::get('/', [
		'as' => 'membership.pricing',
		'uses' => 'MembershipsController@membershipPricing'
		]);

	Route::get('/purchase', [
		'as' => 'select.membership',
		'uses' => 'MembershipsController@selectMembership'
		])->middleware('auth');

	Route::post('/purchase', [
		'as' => 'purchase.membership',
		'uses' => 'MembershipsController@purchaseMembership'
		])->middleware('auth');

	Route::get('/update/{stripe_subscription_id}', [
		'as' => 'change.membership',
		'uses' => 'MembershipsController@changeMembership'
		])->middleware('auth');

	Route::post('/update', [
		'as' => 'update.membership',
		'uses' => 'MembershipsController@updateMembership'
		])->middleware('auth');

	Route::delete('/cancel/{subscription_id}', [
		'as' => 'cancel.membership',
		'uses' => 'MembershipsController@cancelMembership'
		])->middleware('auth');

	Route::post('/reactivate/{subscription_id}', [
		'as' => 'reactivate.membership',
		'uses' => 'MembershipsController@reactivateMembership'
		])->middleware('auth');

});

Route::group(['prefix' => 'subscriptions', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.subscriptions',
		function () {
		return redirect()->route('user.subscriptions', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
		'as' => 'user.subscriptions',
		'uses' => 'RecurringOrdersController@subscriptions'
		]);

	Route::delete('/delete_item/{recurring_order_ref_id}/{item_ref_id}', [
		'as' => 'remove.subscription.item',
		'uses' => 'RecurringOrdersController@removeItem'
		]);

	Route::delete('/delete/{ref_id}', [
		'as' => 'subscription.destroy',
		'uses' => 'RecurringOrdersController@destroySubscription'
		]);
});

Route::group(['prefix' => 'wishlist', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.wishlist',
		function () {
		return redirect()->route('user.wishlist', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
			'as' =>'user.wishlist', 
			'uses' => 'WishlistController@getWishlist',
		]);	

	Route::post('/{product_ref_id}', [
			'as' =>'wishlist.add.product', 
			'uses' => 'WishlistController@addProduct',
		]);	

	Route::delete('/remove/{product_ref_id}', [
			'as' =>'wishlist.remove.product', 
			'uses' => 'WishlistController@removeProduct',
		]);	
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function() {
		Route::get('/', [
			'as' => 'admin.index',
			'uses' => 'AdminController@index']);

		Route::post('/orders/{id}/add-tracking-number/', [
					'as' => 'add.tracking.no',
					'uses' => 'ShipmentsController@addTrackingNumber'
			]);

		Route::post('/orders/{id}/mark-as-unreviewed/', [
					'as' => 'mark.order.unreviewed',
					'uses' => 'OrdersController@markAsUnreviewed'
			]);
		
		Route::get('/orders/{id}/packing-slip/', [
					'as' => 'create.packing.slip',
					'uses' => 'ShipmentsController@createPackingSlip'
			]);

		Route::get('/payments/{payment_id}/refund', [
					'as' => 'create.payment.refund',
					'uses' => 'PaymentsController@createRefund'
			]);

		Route::get('clone-user/{user_id}', [
			'as' => 'clone.user',
			'uses' => 'AdminController@cloneUser'
			]);

		Route::get('products/ingredient-proportions/{product_id}', [
			'as' => 'create.recipe',
			'uses' => 'ProductController@createRecipe'
			]);

		Route::post('products/ingredient-proportions/{product_id}', [
			'as' => 'store.recipe',
			'uses' => 'ProductController@storeRecipe'
			]);

		Route::get('products/ingredient-proportions/{product_id}/edit', [
			'as' => 'edit.recipe',
			'uses' => 'ProductController@editRecipe'
			]);

		Route::patch('products/ingredient-proportions/{product_id}/update', [
			'as' => 'update.recipe',
			'uses' => 'ProductController@updateRecipe'
			]);

		Route::post('/recurring_orders/fill/{recurring_order_id}', [
			'as' => 'fill.recurring.order',
			'uses' => 'RecurringOrdersController@fillRecurringOrder'
			]);

		Route::post('/products/copy-items/{new_product_id}', [
			'as' => 'copy.items',
			'uses' => 'ProductController@copyItems'
			]);

		Route::post('/users/{user_id}/membership', [
			'as' => 'add.user.membership',
			'uses' => 'AdminController@addUserToMembership'
			]);

		Route::post('/credits/{credit_id}/approve', [
			'as' => 'approve.credit.code',
			'uses' => 'CreditsController@approveCreditCode'
			]);

		Route::resource('users', 'UsersController');
		Route::resource('memberships', 'MembershipsController');
		Route::resource('credits', 'CreditsController');
		Route::resource('suppliers', 'SupplierController');
		Route::resource('categories', 'CategoryController');
		Route::resource('subcategories', 'SubCategoryController');
		Route::resource('products', 'ProductController');
		Route::resource('orders', 'OrdersController');
		Route::resource('shipments', 'ShipmentsController');
		Route::resource('payments', 'PaymentsController');
		Route::resource('refunds', 'RefundsController');
		Route::resource('raw_materials', 'RawMaterialController');
		Route::resource('recurring_orders', 'RecurringOrdersController');
		Route::resource('items', 'ItemController');
		Route::resource('purchases', 'PurchasesController');
    });

Route::group(['prefix' => 'checkout'], function() {
		Route::get('/', [
			'as' => 'get.checkout',
			'uses' => 'CheckoutController@getCheckoutPage']);
		
		Route::post('/shipping', [
			'as' => 'shipping.rates',
			'uses' => 'CheckoutController@getShippingRates']);

		Route::post('/payment-form', [
			'as' => 'payment.form',
			'uses' => 'CheckoutController@getPaymentForm']);

		Route::post('/payment', [
			'as' => 'submit.payment',
			'uses' => 'CheckoutController@submitPayment']);
    });

app/Shipment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Shipment extends Model
{
    use SoftDeletes;
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];    

    /**
    * To allow soft deletes
    */  

    protected $dates = ['deleted_at'];

    /**
     * Relationships
     */

    public function order(){
        return $this->belongsTo('App\Order');
    }
}

app/Http/Controllers/ShipmentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Jobs\SendOrdersMail;

use App\Shipment;
use App\Order;

use DB;
use PDF;

class ShipmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shipments = Shipment::has('order')->with('order')->get()->sortByDesc('id');

        $pending_shipments = $shipments->filter(function($shipment){
                                    return $shipment->order->shipped == 0;});
        
        $completed_shipments = $shipments->filter(function($shipment){
                                    return $shipment->order->shipped == 1;});
    
        return view('admin.shipments.index', compact('pending_shipments', 'completed_shipments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Add tracking number
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function addTrackingNumber($id, Request $request)
    {
        $this->validate($request, [
                    'shipping_details' => 'required',
                    'tracking_no' => 'required']);

        $order = Order::find($id);
        $order->tracking_no = $request->tracking_no;
        $order->shipped = 1;

        $order->order_status = "shipped";
        $order->save();

        if ($order->shipment) {
            $order->shipment->status = 'shipped';
            
            $shipping_details = trim($request->shipping_details);
            $order->shipment->provider = substr($shipping_details, 0, strpos($shipping_details, ' '));
            $order->shipment->servicelevel_name = substr($shipping_details, strpos($shipping_details, ' '));

            $order->shipment->save();
        }
        
        $cart_items = unserialize($order->details);

        $subject= "Your order has shipped!";
        $email_view = 'emails.order_shipped';
        
        dispatch(new SendOrdersMail($order, $cart_items, $order->email, $subject, $email_view));

        \Session::flash('success', 'Tracking Number Added, Customer Notified Of Shipment');
        
        return redirect()->back();
    }

    public function createPackingSlip($order_id) 
    {
        $order = Order::find($order_id);
        $cart_items = unserialize($order->details);
        $company_name_id = DB::table('settings')->where('field', 'company_name')->first()->id;
        $company_email_id = DB::table('settings')->where('field', 'company_email')->first()->id;
        $company_address_id = DB::table('settings')->where('field', 'company_address')->first()->id;
        $company_logo_id = DB::table('settings')->where('field', 'company_logo')->first()->id;

        $company_name = DB::table('settings_values')->where('setting_id', $company_name_id)->first()->value;
        $company_email = DB::table('settings_values')->where('setting_id', $company_email_id)->first()->value;
        $company_address = DB::table('settings_values')->where('setting_id', $company_address_id)->first()->value;
        $company_logo = DB::table('settings_values')->where('setting_id', $company_logo_id)->first()->value;

        $pdf = PDF::loadView('admin.packing_slip', compact('order', 'cart_items', 'company_name', 'company_email', 'company_address', 'company_logo'));
        return $pdf->stream();
    }

}

resources/views/admin/shipments/index.blade.php
@extends('layouts.admin_josh.template')
@section('page_title', 'Shipments')
@section('content')
    <div class="row">

        <div class="col-md-12">
            <h3>Shipments</h3>
            <h4>Pending Shipments</h4>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Order & Shipment IDs</th>
                        <th>Order Status</th>
                        <th>Customer</th>
                        <th>Shipping Method</th>
                        <th>Duration</th>
                        <th>Insurance</th>
                        <th>Shippo IDs </th>
                        <th>Notes</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($pending_shipments as $pending_shipment)
                        <tr>
                            <td>{{Carbon\Carbon::parse($pending_shipment->created_at)->format('m/d/Y')}}</td>
                            <td>
                                Order ID: 
                                @if ($pending_shipment->order)
                                    <a href="{{route('orders.show', $pending_shipment->id)}}">{{$pending_shipment->order->id}} / {{$pending_shipment->order->ref_id}}</a>
                                @else
                                    Could not Find Order
                                @endif
                                
                                <br>
                                Shipment ID: {{$pending_shipment->id}}
                            </td>
                            <td>
                                <b>Shippo Status:</b> {{$pending_shipment->status}}
                            </td>

                            <td>{{$pending_shipment->order ? $pending_shipment->order->full_name : 'Could Not Find Order'}}</td>
                            <td>{{$pending_shipment->provider}} - {{$pending_shipment->servicelevel_name
                            }}</td>
                            <td>{{$pending_shipment->days}} days -> {{$pending_shipment->duration_terms}}</td>
                            <td>${{$pending_shipment->insurance_amount ?? 0 }}</td>
                            <td>
                                Shippo Rate ID: {{$pending_shipment->shippo_rate_id}}<br>
                                Shippo Shipment ID: {{$pending_shipment->shippo_shipment_id}}<br>
                                Shippo Parcel ID: {{$pending_shipment->shippo_parcel_id}}<br>
                            </td>
                            <td>{{$pending_shipment->notes}}</td>
                            <td>
                                {!! Form::open(['method' => 'DELETE', 'route' => ['shipments.destroy', 'id' => $pending_shipment->id], 'class' => 'delete']) !!}
                                    <a href="{{route('shipments.edit', ['id'=> $pending_shipment->id])}}" class="btn btn-success"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a></button>
                                    
                                    <div class="btn-group pull-right">
                                        {!! Form::submit("X", ['class' => 'btn btn-danger']) !!}
                                    </div>
                                
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>

            <h4>Completed Shipments</h4>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Order & Shipment IDs</th>
                        <th>Order Status</th>
                        <th>Customer</th>
                        <th>Shipping Method</th>
                        <th>Duration</th>
                        <th>Insurance</th>
                        <th>Shippo IDs </th>
                        <th>Notes</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($completed_shipments as $completed_shipment)
                        <tr>
                            <td>{{Carbon\Carbon::parse($completed_shipment->created_at)->format('m/d/Y')}}</td>
                            <td>
                                Order ID: 
                                @if ($completed_shipment->order)
                                    <a href="{{route('orders.show', $completed_shipment->id)}}">{{$completed_shipment->order->id}} / {{$completed_shipment->order->ref_id}}</a>
                                @else
                                    Could not Find Order
                                @endif
                                
                                <br>
                                Shipment ID: {{$completed_shipment->id}}
                            </td>
                            <td>
                                <b>Shippo Status:</b> {{$completed_shipment->status}}
                            </td>

                            <td>{{$completed_shipment->order ? $completed_shipment->order->full_name : 'Could Not Find Order'}}</td>
                            <td>{{$completed_shipment->provider}} - {{$completed_shipment->servicelevel_name
                            }}</td>
                            <td>{{$completed_shipment->days}} days -> {{$completed_shipment->duration_terms}}</td>
                            <td>${{$completed_shipment->insurance_amount ?? 0 }}</td>
                            <td>
                                Shippo Rate ID: {{$completed_shipment->shippo_rate_id}}<br>
                                Shippo Shipment ID: {{$completed_shipment->shippo_shipment_id}}<br>
                                Shippo Parcel ID: {{$completed_shipment->shippo_parcel_id}}<br>
                            </td>
                            <td>{{$completed_shipment->notes}}</td>
                            <td>
                                {!! Form::open(['method' => 'DELETE', 'route' => ['shipments.destroy', 'id' => $completed_shipment->id], 'class' => 'delete']) !!}
                                    <a href="{{route('shipments.edit', ['id'=> $completed_shipment->id])}}" class="btn btn-success"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a></button>
                                    
                                    <div class="btn-group pull-right">
                                        {!! Form::submit("X", ['class' => 'btn btn-danger']) !!}
                                    </div>
                                
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>        
        </div>

    </div>
    
@endsection