routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    //return view('welcome');
    return view('layouts.organica.homepage');    
});

Auth::routes();

/*Route::get('emails', function(){
	$user = App\User::inRandomOrder()->first();
	$subject = "Failed Job test";
	$email_view = 'emails.notify_admin';

	//dispatch(new App\Jobs\SendAdminEmail($user, $subject, $email_view));
	dispatch(new App\Jobs\SendAdminEmail($subject, $email_view, "TESTING 24141"));
    echo('done');
});
*/

Route::get('/fb/data-feed', [
	'as' => 'facebook.data.feed',
	'uses' => 'ProductController@facebookDataFeedCSV'
]);

Route::get('/search', [
	'as' => 'search.products',
	'uses' => 'ProductController@searchProducts'
]);

//Route::get('/home', 'HomeController@index');

//Webhooks
Route::post('/membership/stripe-webhooks', [
	'uses' => 'StripeWebhooksController@processWebhook'
	]);

Route::get('/contact-us', function () {
    return view('pages.contact');    
});

Route::get('/terms', function () {
    return view('pages.terms');    
});

Route::get('/privacy-policy', function () {
    return view('pages.privacy');    
});

Route::get('/faqs', function () {
    return view('pages.faqs');    
});

Route::get('/giving-back', function () {
    return view('pages.donations');    
});

Route::get('/shipping', function () {
    return view('pages.shipping');    
});

Route::get('/refunds', function () {
    return view('pages.refunds');    
});

Route::get('/gift-cards', function () {
    return view('gift_cards.index');    
});

Route::get('/subscription', function () {
    return view('pages.subscription');    
});

Route::post('gift-cards', [
			'as' => 'purchase.gift.card',
			'uses' =>'CreditsController@purchaseGiftCard']);

Route::post('credits/redeem', [
			'as' => 'redeem.credit.code',
			'uses' =>'CreditsController@redeemCreditCode']);

Route::get('/{cat_slug}/sub/{subcategory_id}/{sub_slug}/', [
			'as' => 'list.products',
			'uses' =>'SubCategoryController@listProducts']);

Route::get('/{cat_slug}/{sub_slug}/pr/{product_id}/{prod_slug}', [
			'as' => 'product.details',
			'uses'=> 'ProductController@productDetails']);

Route::delete('/cart/empty', [
			'as' =>'empty.cart', 
			'uses' => 'CartController@emptyCart',
		]);
Route::resource('/cart', 'CartController');

//For Account
Route::group(['prefix' => 'my-account', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.account',
		function () {
			if (auth()->user()->hasRole('admin')) {
				return redirect('admin');
			}

			return redirect()->route('user.account', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
		'as' =>'user.account', 
		'uses' => 'UsersController@myAccount',
	]);

	Route::get('/{user_ref_id}/edit', [
		'as' =>'edit.account', 
		'uses' => 'UsersController@editAccount',
	]);

	Route::post('/{user_ref_id}/edit', [
		'as' =>'update.account', 
		'uses' => 'UsersController@updateAccount',
	]);

	Route::post('/cart/reorder/{order_ref_id}', [
				'as' => 'reorder.items',
				'uses' =>'CartController@reorderItems']);	
	
	Route::delete('/cancel-order/{order_ref_id}', [
				'as' => 'cancel.order',
				'uses' => 'OrdersController@cancelOrder'
				]);
	
	Route::get('/credits/{user_ref_id}', [
		'as' =>'user.credits', 
		'uses' => 'CreditsController@myCredits',
	]);

	Route::post('/payment-settings/add/{user_ref_id}', [
		'as' =>'add.card', 
		'uses' => 'UsersController@storeCreditCard',
	]);

	Route::get('/payment-settings/{user_ref_id}', [
		'as' =>'edit.card', 
		'uses' => 'UsersController@editCreditCard',
	]);

	Route::post('/payment-settings/{user_ref_id}', [
		'as' =>'update.card', 
		'uses' => 'UsersController@updateCreditCard',
	]);
});

Route::group(['prefix' => 'my-membership'], function () {
	Route::get('/{user_ref_id}', [
		'as' =>'user.memberships', 
		'uses' => 'UsersController@myMemberships',
	]);
});

Route::group(['prefix' => 'membership'], function () {
	Route::get('/', [
		'as' => 'membership.pricing',
		'uses' => 'MembershipsController@membershipPricing'
		]);

	Route::get('/purchase', [
		'as' => 'select.membership',
		'uses' => 'MembershipsController@selectMembership'
		])->middleware('auth');

	Route::post('/purchase', [
		'as' => 'purchase.membership',
		'uses' => 'MembershipsController@purchaseMembership'
		])->middleware('auth');

	Route::get('/update/{stripe_subscription_id}', [
		'as' => 'change.membership',
		'uses' => 'MembershipsController@changeMembership'
		])->middleware('auth');

	Route::post('/update', [
		'as' => 'update.membership',
		'uses' => 'MembershipsController@updateMembership'
		])->middleware('auth');

	Route::delete('/cancel/{subscription_id}', [
		'as' => 'cancel.membership',
		'uses' => 'MembershipsController@cancelMembership'
		])->middleware('auth');

	Route::post('/reactivate/{subscription_id}', [
		'as' => 'reactivate.membership',
		'uses' => 'MembershipsController@reactivateMembership'
		])->middleware('auth');

});

Route::group(['prefix' => 'subscriptions', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.subscriptions',
		function () {
		return redirect()->route('user.subscriptions', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
		'as' => 'user.subscriptions',
		'uses' => 'RecurringOrdersController@subscriptions'
		]);

	Route::delete('/delete_item/{recurring_order_ref_id}/{item_ref_id}', [
		'as' => 'remove.subscription.item',
		'uses' => 'RecurringOrdersController@removeItem'
		]);

	Route::delete('/delete/{ref_id}', [
		'as' => 'subscription.destroy',
		'uses' => 'RecurringOrdersController@destroySubscription'
		]);
});

Route::group(['prefix' => 'wishlist', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.wishlist',
		function () {
		return redirect()->route('user.wishlist', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
			'as' =>'user.wishlist', 
			'uses' => 'WishlistController@getWishlist',
		]);	

	Route::post('/{product_ref_id}', [
			'as' =>'wishlist.add.product', 
			'uses' => 'WishlistController@addProduct',
		]);	

	Route::delete('/remove/{product_ref_id}', [
			'as' =>'wishlist.remove.product', 
			'uses' => 'WishlistController@removeProduct',
		]);	
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function() {
		Route::get('/', [
			'as' => 'admin.index',
			'uses' => 'AdminController@index']);

		Route::post('/orders/{id}/add-tracking-number/', [
					'as' => 'add.tracking.no',
					'uses' => 'ShipmentsController@addTrackingNumber'
			]);

		Route::post('/orders/{id}/mark-as-unreviewed/', [
					'as' => 'mark.order.unreviewed',
					'uses' => 'OrdersController@markAsUnreviewed'
			]);
		
		Route::get('/orders/{id}/packing-slip/', [
					'as' => 'create.packing.slip',
					'uses' => 'ShipmentsController@createPackingSlip'
			]);

		Route::get('/payments/{payment_id}/refund', [
					'as' => 'create.payment.refund',
					'uses' => 'PaymentsController@createRefund'
			]);

		Route::get('clone-user/{user_id}', [
			'as' => 'clone.user',
			'uses' => 'AdminController@cloneUser'
			]);

		Route::get('products/ingredient-proportions/{product_id}', [
			'as' => 'create.recipe',
			'uses' => 'ProductController@createRecipe'
			]);

		Route::post('products/ingredient-proportions/{product_id}', [
			'as' => 'store.recipe',
			'uses' => 'ProductController@storeRecipe'
			]);

		Route::get('products/ingredient-proportions/{product_id}/edit', [
			'as' => 'edit.recipe',
			'uses' => 'ProductController@editRecipe'
			]);

		Route::patch('products/ingredient-proportions/{product_id}/update', [
			'as' => 'update.recipe',
			'uses' => 'ProductController@updateRecipe'
			]);

		Route::post('/recurring_orders/fill/{recurring_order_id}', [
			'as' => 'fill.recurring.order',
			'uses' => 'RecurringOrdersController@fillRecurringOrder'
			]);

		Route::post('/products/copy-items/{new_product_id}', [
			'as' => 'copy.items',
			'uses' => 'ProductController@copyItems'
			]);

		Route::post('/users/{user_id}/membership', [
			'as' => 'add.user.membership',
			'uses' => 'AdminController@addUserToMembership'
			]);

		Route::post('/credits/{credit_id}/approve', [
			'as' => 'approve.credit.code',
			'uses' => 'CreditsController@approveCreditCode'
			]);

		Route::resource('users', 'UsersController');
		Route::resource('memberships', 'MembershipsController');
		Route::resource('credits', 'CreditsController');
		Route::resource('suppliers', 'SupplierController');
		Route::resource('categories', 'CategoryController');
		Route::resource('subcategories', 'SubCategoryController');
		Route::resource('products', 'ProductController');
		Route::resource('orders', 'OrdersController');
		Route::resource('shipments', 'ShipmentsController');
		Route::resource('payments', 'PaymentsController');
		Route::resource('refunds', 'RefundsController');
		Route::resource('raw_materials', 'RawMaterialController');
		Route::resource('recurring_orders', 'RecurringOrdersController');
		Route::resource('items', 'ItemController');
		Route::resource('purchases', 'PurchasesController');
    });

Route::group(['prefix' => 'checkout'], function() {
		Route::get('/', [
			'as' => 'get.checkout',
			'uses' => 'CheckoutController@getCheckoutPage']);
		
		Route::post('/shipping', [
			'as' => 'shipping.rates',
			'uses' => 'CheckoutController@getShippingRates']);

		Route::post('/payment-form', [
			'as' => 'payment.form',
			'uses' => 'CheckoutController@getPaymentForm']);

		Route::post('/payment', [
			'as' => 'submit.payment',
			'uses' => 'CheckoutController@submitPayment']);
    });

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    use SoftDeletes;
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];    

    /**
    * To allow soft deletes
    */  

    protected $dates = ['deleted_at'];

    /**
     * Mutators
     */

    public function getSizeAttribute($value)
    {
        return ucfirst($value);
    }

    public function getColorAttribute($value)
    {
        return ucfirst($value);
    }

    /**
     * Items visible on the front end
     * Must be set to visible and have items that are visible
     * @param  [type] $query [description]
     * @return [type]        [description]
     */
    public function scopeFrontVisible($query)
    {
        return $query->where('is_visible', 1)
                        ->where('discontinued', 0);
    }

    /**
     * Relationships
     */
    

    public function product(){
        return $this->belongsTo('App\Product');
    }

    public function recurring_orders(){
        return $this->belongsToMany('App\RecurringOrder')
                    ->whereNull('item_recurring_order.deleted_at')
                    ->withPivot('price', 'quantity', 'details', 'organic')
                    ->withTimestamps();
    }

    public function available()
    {
        if ($this->is_visible && $this->in_stock && !$this->discontinued){
            return true;
        }
        
        return false;
        
    }

    public function details()
    {
        $details = null;

        if ($this->color) {
            $details .= "Color: $this->color <br>";
        }

        if ($this->scent) {
            $details .= "Scent: $this->scent <br>";
        }

        if ($this->flavor) {
            $details .= "Flavor: $this->flavor <br>";
        }

        if ($this->additional_feature) {
            $details .= "Addtl Feature: $this->additional_feature <br>";
        }

        return  rtrim($details, "<br>");

    }
}

resources/views/layouts/organica/partials/cart_menu.blade.php
@if (!isset($hide_cart))
	<div class="maincart-wrap">
		<a href="javascript:void(0);"><i class="fa fa-shopping-basket"></i>
			<span>{{Cart::content()->count()}}</span>
		</a>
	</div>
	<div class="cart">
		<div class="total-items pb-20 border-bottom mb-15">
			<div class="sub-total clear">
				<strong>{{Cart::count() ?? 0}}</strong>
				<span>{{str_plural('Item', Cart::count())}}</span>
				<span class="pull-right total">
					<span>Cart Subtotal :</span>
					<strong>${{Cart::subtotal()}}</strong>
				</span>
			</div>
			@if (Cart::count() > 0)
				<div class="cart-btn mt-15">
					<a href="{{route('cart.index')}}"><button>View Cart</button></a>
				</div>
			@endif

		</div>
		<div class="cart-items clear mb-15">
			@forelse (Cart::content() as $cart_item)				
				<div class="cart-item ptb-20 border-bottom">
					<div class="cart-img pull-left">
						@if ($cart_item->model->product->image)
							<a href="{{route('product.details', ['cat_slug' => str_slug($cart_item->model->product->subcategory->category->name), 'sub_slug' => str_slug($cart_item->model->product->subcategory->name), 'prod_slug' => str_slug($cart_item->model->product->name), 'product_id' => $cart_item->model->product->id])}}">
								<img src='{{ asset("images/products/{$cart_item->model->product->image}") }}' alt="" />
							</a>
						@endif
					</div>
					<div class="cart-item-details clear">
						<a href="{{route('product.details', ['cat_slug' => str_slug($cart_item->model->product->subcategory->category->name), 'sub_slug' => str_slug($cart_item->model->product->subcategory->name), 'prod_slug' => str_slug($cart_item->model->product->name), 'product_id' => $cart_item->model->product->id])}}">{{$cart_item->name}}</a>
						<br>
						<small>{{$cart_item->model->size ?? ''}}</small>
						<span class="price">${{number_format($cart_item->price, 2)}}</span>
						
						<div class="remove-edit">
							<ul>
								{{--<li><a href="#"><i class="fa fa-cog"></i></a></li>--}}
								{!! Form::open(['method' => 'PATCH', 'route' => ['cart.update', $cart_item->rowId], 'class' => 'form-horizontal']) !!}
									<div class="details-qty pull-left">
										<span>Qty :</span>
										<input type="number" name="qty" min="0" max="12" value="{{$cart_item->qty}}">			
									</div>
							        

								    <div class="btn-group pull-left">
								        {!! Form::submit("Update", ['class' => 'btn btn-success']) !!}
								    </div>
								{!! Form::close() !!}
								&nbsp;&nbsp;&nbsp;
								<li>
									{!! Form::open(['method' => 'DELETE', 'route' => ['cart.destroy', 'row_id' => $cart_item->rowId], 'class' => 'delete']) !!}			
									    <div class="btn-group pull-right">
									        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger']) !!}
									    </div>
									{!! Form::close() !!}
							</ul>
						</div>
					</div>
				</div>
			@empty
				<div>
					<center>No Items In Cart</center>
				</div>
			@endforelse
		</div>
		@if (Cart::count() > 0)
			<div class="organic-btn pt-20 text-center border-top">
				<a href="{{route('get.checkout')}}">Go to Checkout</a>
			</div>
		@endif
	</div> 
@endif

resources/views/layouts/organica/partials/facebook_like_button.blade.php
{{-- Facebook Link & Like --}}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://facebook.com/MountainMystCO" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a> &nbsp;
<a href="https://instagram.com/MountainMystCO" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a> &nbsp;
{{-- <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Ffacebook.com%2FMountainMystCO&width=52&layout=button&action=like&size=small&show_faces=false&share=false&height=20&appId" width="52" height="20" style="border:none;overflow:hidden;" scrolling="no" frameborder="0" allowTransparency="true"></iframe> --}}

resources/views/layouts/organica/partials/footer.blade.php
<!-- newsletter area start -->
{{--
<div class="home2-newsletter-area mt-60" style="background:url({{asset('images/footer_background.png')}}) no-repeat scroll 0 0;">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="newsletter home2-newsletter">
					
					<span>
						<a href="mailto:Contact@Mountain-Myst.com"><i class="fa fa-envelope-o "></i>  Contact@Mountain-Myst.com</a>
					</span>
				</div>
				
				<div class="socialicon ptb-50">
					<ul>
						<li>
							<a href="#"><i class="fa fa-envelope-o "></i></a>

						</li>
					</ul>
				</div>
				
			</div>
			
			<div class="col-md-8 col-sm-8  col-xs-12">
				<div class="newsletter home2-newsletter">
					<span>Sign up for send newsletter</span>
					<form action="#">
						<input type="email" placeholder="Enter your email address"/>
						<button>Subscribe <i class="fa fa-long-arrow-right"></i></button>
					</form>
				</div>
			</div>
			
		</div>
	</div>
</div>
--}}
<!-- newsletter area end -->
<footer>
	{{-- 
	<div class="top-footer ptb-20 bg-2">
		<div class="container">
			<div class="row">
				<div class="col-md-6  col-sm-6  col-xs-12">
					<div class="contact clear">
						<div class="icon">
							<i class="fa fa-envelope-o"></i>
							<span>Do you have </span>
							<span> a question?</span>
						</div>
						<div class="text">
							<p><a href="mailto:Contact@Mountain-Myst.com">
							Contact@Mountain-Myst.com </a></p>
						</div>
					</div>
				</div> 
				<div class="col-md-4  col-sm-6 col-xs-12">
					<div class="contact clear">
						<div class="icon">
							<i class="fa fa-phone"></i>
							<span>Do you have </span>
							<span> a question?</span>
						</div>
						<div class="text">
							+0123 456 789
						</div>
					</div>
				</div>
				
				<div class="col-md-4 hidden-sm  col-xs-12">
					<div class="contact clear">
						<div class="icon">
							<i class="fa fa-life-saver"></i>
							<span> Support  </span>
							<span>question?</span>
						</div>
						<div class="text">
							<p>support@organica.com </p>
						</div>
					</div>
				</div>				
			</div>
		</div>
	</div>
	 --}}
	<!-- contuct area end -->
	<!-- footer menu area start -->
	<div class="footer-medil-area bg-2">
		<div class="container">
			<div class="row">
				<div class="col-md-3 border-right col-sm-3  col-xs-12">
					<div class="footer-wrap pb-50">
						<div class="footer-static-title  text-uppercase  mt-50 mb-30">
							<h3>Information</h3>
						</div>
						<div class="footer-menu  text-uppercase">
							<ul>
								@if (isset($membership_active) && $membership_active)
									<li><a href="{{url('/membership')}}">Membership</a></li>
								@endif
								<li><a href="{{url('/subscription')}}">Subscription</a></li>
								<li><a href="{{url('/gift-cards')}}">Gift Cards</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-md-3 border-right col-sm-3  col-xs-12">
					<div class="footer-wrap pb-50">
						<div class="footer-static-title  text-uppercase  mt-50 mb-30">
							<h3>My Account</h3>
						</div>
						<div class="footer-menu  text-uppercase">
							<ul>
								<li><a href="{{route('my.account')}}">My Account</a></li>
								<li><a href="{{route('my.wishlist')}}">My Wish List</a></li>
								<li><a href="{{route('my.subscriptions')}}">My Subscriptions</a></li>				
							</ul>
						</div>
					</div>
				</div>
				<div class="col-md-3  border-right col-sm-3  col-xs-12">
					<div class="footer-wrap pb-50">
						<div class="footer-static-title  text-uppercase  mt-50 mb-30">
							<h3>Policies</h3>
						</div>
						<div class="footer-menu  text-uppercase">
							<ul>
								<li><a href="{{url('/shipping')}}">Shipping Policy</a></li>
								<li><a href="{{url('/privacy-policy')}}">Privacy Policy</a></li>
								<li><a href="{{url('/terms')}}">Terms Of Use</a></li>
								<li><a href="{{url('/refunds')}}">Refunds & Returns</a></li>
								{{-- <li><a href="{{url('/faqs')}}">FAQs</a></li> --}}
							</ul>
						</div>
					</div>
				</div>
				<div class="col-md-3  col-sm-3  col-xs-12">
					<div class="footer-wrap pb-50">
						<div class="footer-static-title  text-uppercase  mt-50 mb-30">
							<h3>Extras</h3>
						</div>
						<div class="footer-menu  text-uppercase">
							<ul>
								<li><a href="https://www.ewg.org/skindeep/search.php" target="_blank">EWG Skin Deep Cosmetics Database</a></li>
								<li><a href="{{url('/giving-back')}}">Giving Back</a></li>
								<li><a href="{{url('/contact-us')}}">Contact Us</a></li>
								{{-- <li><a href="#">Referral Policy  (ADD LINK)</a></li> --}}
								
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- footer menu area end -->
	<!-- copy right area start -->
	<div class="footer-bottom ptb-20 bg-4">
		<div class="container">
			<div class="row">
				<div {{-- class="col-lg-6 col-md-6 col-sm-6 col-xs-12" --}}>
					<div class="copyright">
						
						<small><em>The content on this website is for educational purposes only. This information has not been evaluated by the Food and Drug Administration. This information is not intended to diagnose, treat, cure, or prevent any disease. </em>
						</small>
					</div>
				</div>	
			</div>
			<br>
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<div class="copyright">
						<span>Copyright &copy; Mountain Myst, {{date('Y')}}</span>
					</div>
				</div>	
			</div>
			

			
		</div>
	</div>
	<!-- copy right area end -->
</footer>

resources/views/layouts/organica/partials/header.blade.php
<header class="header-area ptb-30">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-xs-12">
				<div class="logo">
					<a href="{{url('/')}}">
						<img src="{{asset('images/logo/mountain_myst_logo.png')}}" alt="" />
					</a>
				</div>
			</div>
			<div class="col-md-8 col-sm-10 col-xs-10">
				<div class="mainmenu-area">
					<div class="top-bar clear">
						<div class="top-bar-left pull-left hidden-xs">
							<div class="hotline pull-left hidden-sm">
								
								<p><a href="{{url('/shipping')}}"><b><i class="fa fa-truck"></i> Free Shipping On Orders Over ${{config('other_constants.free_shipping_amount')}}!</b></a></p>
								
							</div>
						</div>
						{{--Search Box--}}
						
						<div class="top-bar-right">
							<div class="search-box">
								{!! Form::open(['method' => 'GET', 'url' => 'search', 'class' => 'form-horizontal']) !!}
								
								    <input type="search" name="query" id="query" placeholder="Search here ....."/>
									<button type="submit"><i class="fa fa-search"></i></button>
								
								{!! Form::close() !!}
							</div>
						</div>
						
						<div class="top-bar-right pull-right">
				           	{{-- <a href="mailto:Contact@Mountain-Myst.com">Contact@Mountain-Myst.com</a> |  --}}
							@if (isset($membership_active) && $membership_active)
									<a href="{{url('/membership')}}">Membership</a> | 
								@endif
							<a href="{{url('/gift-cards')}}">Gift Cards</a>	|

				            @if (Auth::user())
				                    <a href="{{route('user.account', Auth::user()->ref_id)}}">
				                    My Account
				                    </a> |    
				                    <a href="{{route('user.wishlist', Auth::user()->ref_id)}}">
				                    Wish List <b>({{Auth::user()->wishlist->count()}})</b>
				                    </a> |    
				                    <a href="{{ route('logout') }}"
				                        onclick="event.preventDefault();
				                                 document.getElementById('logout-form').submit();">
				                        Logout
				                    </a>

				                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
				                        {{ csrf_field() }}
				                    </form>
				                
				            @else
				                <a href="{{ url('/login') }}">Login</a>    
				            @endif
				            
				            {{-- Facebook Link & Like --}}
				            @include('layouts.organica.partials.facebook_like_button')
						</div>
					</div>
					<div class="mainmenu dropdown hidden-xs hidden-sm">
						<nav class="pull-right">
							@include('layouts.organica.partials.topmenu')
						</nav>
					</div>
				</div>
			</div>
			{{--Cart--}}
			<div class="col-md-1 col-sm-2 col-xs-2">
				<div class="cart-area">
					@include('layouts.organica.partials.cart_menu')
				</div>
			</div>
		</div>
	</div>
	<!-- mobail-menu -->
	<div class="mobail-menu-area">
		<div class="container">
			<div class="row">
				<div class=" hidden-lg hidden-md col-sm-12">
					<div class="mobail-menu-active">
						@include('layouts.organica.partials.topmenu_mobile')
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

resources/views/layouts/organica/partials/template_scripts.blade.php
<!-- jquery latest version -->
<script src="{{asset('organica/js/vendor/jquery-1.12.4.min.js')}}"></script>
	<!-- bootstrap js -->
<script src="{{asset('organica/js/bootstrap.min.js')}}"></script>
	<!-- owl.carousel.2.0.0-beta.2.4 css -->
<script src="{{asset('organica/js/owl.carousel.min.js')}}"></script>
	<!-- meanmenu js -->
<script src="{{asset('organica/js/jquery.meanmenu.js')}}"></script>
	<!-- jquery-ui js -->
<script src="{{asset('organica/js/jquery-ui.min.js')}}"></script>
	<!-- nivo-slider js -->
<script src="{{asset('organica/js/jquery.nivo.slider.pack.js')}}"></script>
	<!-- jquery countdown js -->
<script src="{{asset('organica/js/jquery.countdown.min.js')}}"></script>
	<!-- wow js -->
<script src="{{asset('organica/js/wow.min.js')}}"></script>
	<!-- plugins js -->
<script src="{{asset('organica/js/plugins.js')}}"></script>
	<!-- main js -->
<script src="{{asset('organica/js/main.js')}}"></script>

resources/views/layouts/organica/partials/toplinks.blade.php
<li><a href="{{url('giving-back')}}">Giving Back</a></li>
{{--<li><a href="#">Membership</a></li>
<li><a href="#">Clearance</a></li>
<li><a href="#">Contact Us</a></li>--}}