routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    //return view('welcome');
    return view('layouts.organica.homepage');    
});

Auth::routes();

/*Route::get('emails', function(){
	$user = App\User::inRandomOrder()->first();
	$subject = "Failed Job test";
	$email_view = 'emails.notify_admin';

	//dispatch(new App\Jobs\SendAdminEmail($user, $subject, $email_view));
	dispatch(new App\Jobs\SendAdminEmail($subject, $email_view, "TESTING 24141"));
    echo('done');
});
*/

Route::get('/fb/data-feed', [
	'as' => 'facebook.data.feed',
	'uses' => 'ProductController@facebookDataFeedCSV'
]);

Route::get('/search', [
	'as' => 'search.products',
	'uses' => 'ProductController@searchProducts'
]);

//Route::get('/home', 'HomeController@index');

//Webhooks
Route::post('/membership/stripe-webhooks', [
	'uses' => 'StripeWebhooksController@processWebhook'
	]);

Route::get('/contact-us', function () {
    return view('pages.contact');    
});

Route::get('/terms', function () {
    return view('pages.terms');    
});

Route::get('/privacy-policy', function () {
    return view('pages.privacy');    
});

Route::get('/faqs', function () {
    return view('pages.faqs');    
});

Route::get('/giving-back', function () {
    return view('pages.donations');    
});

Route::get('/shipping', function () {
    return view('pages.shipping');    
});

Route::get('/refunds', function () {
    return view('pages.refunds');    
});

Route::get('/gift-cards', function () {
    return view('gift_cards.index');    
});

Route::get('/subscription', function () {
    return view('pages.subscription');    
});

Route::post('gift-cards', [
			'as' => 'purchase.gift.card',
			'uses' =>'CreditsController@purchaseGiftCard']);

Route::post('credits/redeem', [
			'as' => 'redeem.credit.code',
			'uses' =>'CreditsController@redeemCreditCode']);

Route::get('/{cat_slug}/sub/{subcategory_id}/{sub_slug}/', [
			'as' => 'list.products',
			'uses' =>'SubCategoryController@listProducts']);

Route::get('/{cat_slug}/{sub_slug}/pr/{product_id}/{prod_slug}', [
			'as' => 'product.details',
			'uses'=> 'ProductController@productDetails']);

Route::delete('/cart/empty', [
			'as' =>'empty.cart', 
			'uses' => 'CartController@emptyCart',
		]);
Route::resource('/cart', 'CartController');

//For Account
Route::group(['prefix' => 'my-account', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.account',
		function () {
			if (auth()->user()->hasRole('admin')) {
				return redirect('admin');
			}

			return redirect()->route('user.account', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
		'as' =>'user.account', 
		'uses' => 'UsersController@myAccount',
	]);

	Route::get('/{user_ref_id}/edit', [
		'as' =>'edit.account', 
		'uses' => 'UsersController@editAccount',
	]);

	Route::post('/{user_ref_id}/edit', [
		'as' =>'update.account', 
		'uses' => 'UsersController@updateAccount',
	]);

	Route::post('/cart/reorder/{order_ref_id}', [
				'as' => 'reorder.items',
				'uses' =>'CartController@reorderItems']);	
	
	Route::delete('/cancel-order/{order_ref_id}', [
				'as' => 'cancel.order',
				'uses' => 'OrdersController@cancelOrder'
				]);
	
	Route::get('/credits/{user_ref_id}', [
		'as' =>'user.credits', 
		'uses' => 'CreditsController@myCredits',
	]);

	Route::post('/payment-settings/add/{user_ref_id}', [
		'as' =>'add.card', 
		'uses' => 'UsersController@storeCreditCard',
	]);

	Route::get('/payment-settings/{user_ref_id}', [
		'as' =>'edit.card', 
		'uses' => 'UsersController@editCreditCard',
	]);

	Route::post('/payment-settings/{user_ref_id}', [
		'as' =>'update.card', 
		'uses' => 'UsersController@updateCreditCard',
	]);
});

Route::group(['prefix' => 'my-membership'], function () {
	Route::get('/{user_ref_id}', [
		'as' =>'user.memberships', 
		'uses' => 'UsersController@myMemberships',
	]);
});

Route::group(['prefix' => 'membership'], function () {
	Route::get('/', [
		'as' => 'membership.pricing',
		'uses' => 'MembershipsController@membershipPricing'
		]);

	Route::get('/purchase', [
		'as' => 'select.membership',
		'uses' => 'MembershipsController@selectMembership'
		])->middleware('auth');

	Route::post('/purchase', [
		'as' => 'purchase.membership',
		'uses' => 'MembershipsController@purchaseMembership'
		])->middleware('auth');

	Route::get('/update/{stripe_subscription_id}', [
		'as' => 'change.membership',
		'uses' => 'MembershipsController@changeMembership'
		])->middleware('auth');

	Route::post('/update', [
		'as' => 'update.membership',
		'uses' => 'MembershipsController@updateMembership'
		])->middleware('auth');

	Route::delete('/cancel/{subscription_id}', [
		'as' => 'cancel.membership',
		'uses' => 'MembershipsController@cancelMembership'
		])->middleware('auth');

	Route::post('/reactivate/{subscription_id}', [
		'as' => 'reactivate.membership',
		'uses' => 'MembershipsController@reactivateMembership'
		])->middleware('auth');

});

Route::group(['prefix' => 'subscriptions', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.subscriptions',
		function () {
		return redirect()->route('user.subscriptions', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
		'as' => 'user.subscriptions',
		'uses' => 'RecurringOrdersController@subscriptions'
		]);

	Route::delete('/delete_item/{recurring_order_ref_id}/{item_ref_id}', [
		'as' => 'remove.subscription.item',
		'uses' => 'RecurringOrdersController@removeItem'
		]);

	Route::delete('/delete/{ref_id}', [
		'as' => 'subscription.destroy',
		'uses' => 'RecurringOrdersController@destroySubscription'
		]);
});

Route::group(['prefix' => 'wishlist', 'middleware' => 'auth'], function () {
	Route::get('/', [
		'as' => 'my.wishlist',
		function () {
		return redirect()->route('user.wishlist', ['user_ref_id' => auth()->user()->ref_id]);
		}]);

	Route::get('/{user_ref_id}', [
			'as' =>'user.wishlist', 
			'uses' => 'WishlistController@getWishlist',
		]);	

	Route::post('/{product_ref_id}', [
			'as' =>'wishlist.add.product', 
			'uses' => 'WishlistController@addProduct',
		]);	

	Route::delete('/remove/{product_ref_id}', [
			'as' =>'wishlist.remove.product', 
			'uses' => 'WishlistController@removeProduct',
		]);	
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function() {
		Route::get('/', [
			'as' => 'admin.index',
			'uses' => 'AdminController@index']);

		Route::post('/orders/{id}/add-tracking-number/', [
					'as' => 'add.tracking.no',
					'uses' => 'ShipmentsController@addTrackingNumber'
			]);

		Route::post('/orders/{id}/mark-as-unreviewed/', [
					'as' => 'mark.order.unreviewed',
					'uses' => 'OrdersController@markAsUnreviewed'
			]);
		
		Route::get('/orders/{id}/packing-slip/', [
					'as' => 'create.packing.slip',
					'uses' => 'ShipmentsController@createPackingSlip'
			]);

		Route::get('/payments/{payment_id}/refund', [
					'as' => 'create.payment.refund',
					'uses' => 'PaymentsController@createRefund'
			]);

		Route::get('clone-user/{user_id}', [
			'as' => 'clone.user',
			'uses' => 'AdminController@cloneUser'
			]);

		Route::get('products/ingredient-proportions/{product_id}', [
			'as' => 'create.recipe',
			'uses' => 'ProductController@createRecipe'
			]);

		Route::post('products/ingredient-proportions/{product_id}', [
			'as' => 'store.recipe',
			'uses' => 'ProductController@storeRecipe'
			]);

		Route::get('products/ingredient-proportions/{product_id}/edit', [
			'as' => 'edit.recipe',
			'uses' => 'ProductController@editRecipe'
			]);

		Route::patch('products/ingredient-proportions/{product_id}/update', [
			'as' => 'update.recipe',
			'uses' => 'ProductController@updateRecipe'
			]);

		Route::post('/recurring_orders/fill/{recurring_order_id}', [
			'as' => 'fill.recurring.order',
			'uses' => 'RecurringOrdersController@fillRecurringOrder'
			]);

		Route::post('/products/copy-items/{new_product_id}', [
			'as' => 'copy.items',
			'uses' => 'ProductController@copyItems'
			]);

		Route::post('/users/{user_id}/membership', [
			'as' => 'add.user.membership',
			'uses' => 'AdminController@addUserToMembership'
			]);

		Route::post('/credits/{credit_id}/approve', [
			'as' => 'approve.credit.code',
			'uses' => 'CreditsController@approveCreditCode'
			]);

		Route::resource('users', 'UsersController');
		Route::resource('memberships', 'MembershipsController');
		Route::resource('credits', 'CreditsController');
		Route::resource('suppliers', 'SupplierController');
		Route::resource('categories', 'CategoryController');
		Route::resource('subcategories', 'SubCategoryController');
		Route::resource('products', 'ProductController');
		Route::resource('orders', 'OrdersController');
		Route::resource('shipments', 'ShipmentsController');
		Route::resource('payments', 'PaymentsController');
		Route::resource('refunds', 'RefundsController');
		Route::resource('raw_materials', 'RawMaterialController');
		Route::resource('recurring_orders', 'RecurringOrdersController');
		Route::resource('items', 'ItemController');
		Route::resource('purchases', 'PurchasesController');
    });

Route::group(['prefix' => 'checkout'], function() {
		Route::get('/', [
			'as' => 'get.checkout',
			'uses' => 'CheckoutController@getCheckoutPage']);
		
		Route::post('/shipping', [
			'as' => 'shipping.rates',
			'uses' => 'CheckoutController@getShippingRates']);

		Route::post('/payment-form', [
			'as' => 'payment.form',
			'uses' => 'CheckoutController@getPaymentForm']);

		Route::post('/payment', [
			'as' => 'submit.payment',
			'uses' => 'CheckoutController@submitPayment']);
    });

resources/views/layouts/admin_josh/sidenav.blade.php
<section class="sidebar ">
    <div class="page-sidebar  sidebar-nav">
        
        <div class="nav_icons"> 
            <ul class="sidebar_threeicons">
                <li>
                    <a href="{{route('users.index')}}">
                        <i class="livicon" data-name="users" title="Users List" data-size="25" data-c="#01bc8c" data-hc="#01bc8c" data-loop="true"></i>
                    </a>
                </li>
                <li>
                    <a href="{{route('products.index')}}">
                        <i class="livicon" data-name="leaf" title="Products" data-c="#F89A14" data-hc="#F89A14" data-size="25" data-loop="true"></i>
                    </a>                
                </li>
                <li>
                    <a href="{{route('payments.index')}}">
                        <i class="livicon" data-name="piggybank" title="Payments" data-c="#418BCA" data-hc="#418BCA" data-size="25" data-loop="true"></i>
                    </a>
                </li>
                <li>
                    <a href="{{route('orders.index')}}">
                        <i class="livicon" data-c="#EF6F6C" title="Orders" data-hc="#EF6F6C" data-name="shopping-cart" data-size="25" data-loop="true"></i>
                    </a>
                </li>
            </ul>
        </div>
        
        <div class="clearfix"></div>
        <!-- BEGIN SIDEBAR MENU -->
        <ul id="menu" class="page-sidebar-menu">
            <li class="active">
                <a href="{{route('admin.index')}}">
                    <i class="livicon" data-name="home" data-size="18" data-c="#418BCA" data-hc="#418BCA" data-loop="true"></i>
                    <span class="title">Dashboard</span>
                </a>
            </li>

            <li>
                <a href="{{route('orders.index')}}">
                    <i class="livicon" data-name="shopping-cart" data-size="18" data-c="#EF6F6C" data-hc="#EF6F6C" data-loop="true"></i>
                    <span class="title">New Orders</span>
                    <span class="badge badge-danger">{{App\Order::pending()->count()}}</span>
                </a>
            </li>
            <li>
                <a href="{{route('recurring_orders.index')}}">
                    <i class="livicon" data-name="shopping-cart" data-c="#5bc0de" data-hc="#5bc0de" data-size="18" data-loop="true"></i>
                    <span class="title">Recurring Orders</span>
                    {{-- <span class="fa arrow"></span> --}}
                </a>
            </li>
            <li>
                <a href="{{route('users.index')}}">
                    <i class="livicon" data-name="users" data-size="18" data-c="#00bc8c" data-hc="#00bc8c" data-loop="true"></i>
                    <span class="title">Users</span>
                    <?php $new_users = App\User::where('created_at', '>', Carbon\Carbon::now()->subWeek())->count();?>
                    @if(    $new_users)
                        <span class="badge badge-danger">{{$new_users}}</span>
                    @endif
                    
                </a>
            </li>
            <li>
                <a href="{{route('memberships.index')}}">
                    <i class="livicon" data-name="users" data-size="18" data-c="#00bc8c" data-hc="#00bc8c" data-loop="true"></i>
                    <span class="title">Memberships</span>
                </a>
            </li>
            <li>
                <a href="{{route('credits.index')}}">
                    <i class="livicon" data-name="money" data-size="18" data-c="#00bc8c" data-hc="#00bc8c" data-loop="true"></i>
                    <span class="title">Credits & Gift Cards</span>
                </a>
            </li>
            <li>
                <a href="{{route('products.index')}}">
                    <i class="livicon" data-name="leaf" data-c="#418BCA" data-hc="#418BCA" data-size="18" data-loop="true"></i>
                    <span class="title">Products</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('products.index')}}">
                            <i class="fa fa-angle-double-right"></i> Products List
                        </a>
                    </li>
                    <li>
                        <a href="{{route('items.index')}}">
                            <i class="fa fa-angle-double-right"></i> Items List
                        </a>
                    </li>
                </ul>
            </li>
            {{-- <li>
                <a href="#">
                    <i class="livicon" data-name="list" data-c="#00bc8c" data-hc="#00bc8c" data-size="18" data-loop="true"></i>
                    <span class="title">Items</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('items.index')}}">
                            <i class="fa fa-angle-double-right"></i> Items List
                        </a>
                    </li>
                    <li>
                        <a href="{{route('items.create')}}">
                            <i class="fa fa-angle-double-right"></i> Add An Item
                        </a>
                    </li>
                </ul>
            </li> --}}
            <li>
                <a href="#">
                    <i class="livicon" data-name="list" data-c="#F89A14" data-hc="#F89A14" data-size="18" data-loop="true"></i>
                    <span class="title">Categories</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('categories.index')}}"> <i class="fa fa-angle-double-right"></i> All Categories </a>
                    </li>
                    <li>
                        <a href="{{route('categories.create')}}"> <i class="fa fa-angle-double-right"></i> Add A New Category </a>
                    </li>
                    <li>
                        <a href="{{route('subcategories.index')}}"> <i class="fa fa-angle-double-right"></i> All Subcategories </a>
                    </li>
                    <li>
                        <a href="{{route('subcategories.create')}}"> <i class="fa fa-angle-double-right"></i> Add A New Subcategory </a>
                    </li>
                </ul>
            </li>
            {{-- <li>
                <a href="#">
                    <i class="livicon" data-name="list" data-c="#5bc0de" data-hc="#5bc0de" data-size="18" data-loop="true"></i>
                    <span class="title">Subcategories</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('subcategories.index')}}"> <i class="fa fa-angle-double-right"></i> All Subcategories </a>
                    </li>
                    <li>
                        <a href="{{route('subcategories.create')}}"> <i class="fa fa-angle-double-right"></i> Add A New Subcategory </a>
                    </li>
                </ul>
            </li> --}}
            <li>
                <a href="#">
                    <i class="livicon" data-name="piggybank" data-c="#5bc0de" data-hc="#5bc0de" data-size="18" data-loop="true"></i>
                    <span class="title">Payments & Refunds</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('payments.index')}}">
                            <i class="fa fa-angle-double-right"></i> Payments
                        </a>
                    </li>
                    <li>
                        <a href="{{route('refunds.index')}}">
                            <i class="fa fa-angle-double-right"></i> Refunds
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-angle-double-right"></i> Incomplete Payments (TO DO)
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="livicon" data-name="truck" data-c="#F89A14" data-hc="#F89A14" data-size="18" data-loop="true"></i>
                    <span class="title">Shipments</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('shipments.index')}}">
                            <i class="fa fa-angle-double-right"></i> All Shipments
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-angle-double-right"></i> Pending Shipments (To DO)
                        </a>
                    </li>
                </ul>
            </li>
            {{-- <li>
                <a href="#">
                    <i class="livicon" data-name="shopping-cart-out" data-size="18" data-c="#00bc8c" data-hc="#00bc8c" data-loop="true"></i>
                    <span class="title">Refunds</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('refunds.index')}}">
                            <i class="fa fa-angle-double-right"></i> All Refunds
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-angle-double-right"></i> Pending Refunds
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-angle-double-right"></i> Completed Refunds
                        </a>
                    </li>
                </ul>
            </li> --}}
            
            <li>
                <a href="#">
                    <i class="livicon" data-name="list" data-c="#418BCA" data-hc="#418BCA" data-size="18" data-loop="true"></i>
                    <span class="title">Suppliers & Materials</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('suppliers.index')}}">
                            <i class="fa fa-angle-double-right"></i> Suppliers
                        </a>
                    </li>
                    <li>
                        <a href="{{route('raw_materials.index')}}">
                            <i class="fa fa-angle-double-right"></i> Raw Materials
                        </a>
                    </li>
                </ul>
            </li>
            {{-- <li>
                <a href="#">
                    <i class="livicon" data-name="apple" data-size="18" data-c="#00bc8c" data-hc="#00bc8c" data-loop="true"></i>
                    <span class="title">Raw Materials</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('raw_materials.index')}}">
                            <i class="fa fa-angle-double-right"></i> List
                        </a>
                    </li>
                    <li>
                        <a href="{{route('raw_materials.create')}}">
                            <i class="fa fa-angle-double-right"></i> Add Raw Material 
                        </a>
                    </li>
                </ul>
            </li> --}}

            <li>
                <a href="#">
                    <i class="livicon" data-name="credit-card" data-size="18" data-c="#5bc0de" data-hc="#5bc0de" data-loop="true"></i>
                    <span class="title">Purchases & Expenses</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('purchases.index')}}">
                            <i class="fa fa-angle-double-right"></i> Purchases List
                        </a>
                    </li>
                    {{-- <li>
                        <a href="{{route('purchases.create')}}">
                            <i class="fa fa-angle-double-right"></i> Add A Purchase
                        </a>
                    </li> --}}
                    <li>
                        <a href="#">
                            <i class="fa fa-angle-double-right"></i> Expenses List (To Do)
                        </a>
                    </li>
                </ul>
            </li>
            
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
</section>
<!-- /.sidebar -->

resources/views/layouts/admin_josh/template.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Admin Area - @yield('page_title', 'Dashboard')</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <!-- global css -->
    <link href="{{asset('admin_josh/css/app.css')}}" rel="stylesheet" type="text/css" />
    <!-- end of global css -->
    <!--page level css -->
        @yield('page_level_css')
    <!--end of page level css-->
</head>

<body class="skin-josh">
    <header class="header">
        @include('layouts.admin_josh.header')
    </header>

    <div class="wrapper row-offcanvas row-offcanvas-left">
        <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                @include('layouts.admin_josh.sidenav')
            </aside>
        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side" style="overflow-x: scroll;">
            @include('layouts.alerts')
            {{--
            <div class="alert alert-success alert-dismissable margin5">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Success:</strong> You have successfully logged in.
            </div>
            --}}

            <!-- Main content -->
            <section class="content-header">
                <h1>@yield('page_title','Dashboard')</h1>
                <ol class="breadcrumb">
                    <li class="active">
                        <a href="#">
                            <i class="livicon" data-name="home" data-size="14" data-color="#333" data-hovercolor="#333"></i> Dashboard
                        </a>
                    </li>
                </ol>
            </section>
            <section class="content">
                @yield('content')
            </section>
                
        </aside>
        <!-- right-side -->
    </div>
    <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Return to top" data-toggle="tooltip" data-placement="left">
        <i class="livicon" data-name="plane-up" data-size="18" data-loop="true" data-c="#fff" data-hc="white"></i>
    </a>
    <!-- global js -->
    <script src="{{asset('admin_josh/js/app.js')}}" type="text/javascript"></script>
    <!-- end of global js -->
    <!-- begining of page level js -->
        @yield('page_level_js')
    <!-- end of page level js -->
    <script>
        $(".delete").on("submit", function(){
            return confirm("Are you sure you want to delete?");
        });
    </script>
</body>

</html>